openapi: 3.0.0
info:
  title: Sample API
  description: A sample API to demonstrate OpenAPI specification rendering with Redoc
  version: 1.0.0
  contact:
    email: support@example.com
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
tags:
  - name: users
    description: Operations about users
  - name: products
    description: Operations about products
paths:
  /users:
    get:
      summary: Get all users
      description: Returns a list of users
      operationId: getUsers
      tags:
        - users
      parameters:
        - name: limit
          in: query
          description: Maximum number of users to return
          required: false
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    post:
      summary: Create a user
      description: Creates a new user
      operationId: createUser
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /users/{userId}:
    get:
      summary: Get user by ID
      description: Returns a single user
      operationId: getUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          description: ID of the user to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
  /products:
    get:
      summary: Get all products
      description: Returns a list of products
      operationId: getProducts
      tags:
        - products
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: string
          example: "Jane Doe"
        email:
          type: string
          format: email
          example: "jane.doe@example.com"
        status:
          type: string
          enum: [active, inactive, pending]
          example: "active"
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - name
        - email
        - status
    UserInput:
      type: object
      properties:
        name:
          type: string
          example: "Jane Doe"
        email:
          type: string
          format: email
          example: "jane.doe@example.com"
      required:
        - name
        - email
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        name:
          type: string
          example: "Smartphone XYZ"
        price:
          type: number
          format: float
          example: 599.99
        category:
          type: string
          example: "Electronics"
        inStock:
          type: boolean
          example: true
      required:
        - id
        - name
        - price
        - category